[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "twitter-v2"
authors = [{ name = "Omar MHAIMDAT", email = "omarmhaimdat@gmail.com" }]
version = "0.1.0"
description = "Python client for interacting with Twitter V2 API available at "
requires-python = ">=3.7"
dependencies = ["aiohttp", "requests"]
